# NOTE: Activate 2 nodes in parallel on CircleCI
version: 2
jobs:
  "3.5":
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install requirements
          command: |
            pyenv local 3.5.2
            pip install -U pip ipdb tox tox-pyenv
      - run:
          name: test
          command: |
            tox -e py35
      - run:
          name: install and train
          command: |
            make EPOCHS_TRAIN=${EPOCHS_TRAIN} install train
      - store_artifacts:
          path: ~/repo/seldon/models
      - run:
          name: build and push seldon image
          command: |
            docker login -u=${DOCKER_USERNAME} -p=${DOCKER_PASSWORD}
            VERSION="$(echo $CIRCLE_SHA1 | cut -c -7)" make seldon-build seldon-push
  "3.6":
    docker:
    - image: python:3.6
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          pip install tox
    - run:
        name: test
        command: |
          tox -e py36
    - run:
        name: install
        command: |
          make install
  gce:
    docker:
    - image: google/cloud-sdk
    working_directory: ~/repo
    steps:
    - checkout
    - run:
       name: configure gcloud client
       command: |
         echo ${GOOGLE_AUTH} > ${HOME}/gcp-key.json
         gcloud auth activate-service-account --key-file ${HOME}/gcp-key.json
         gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
         gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
         gcloud --quiet container clusters get-credentials ${GOOGLE_CLUSTER_NAME}
    - run:
        name: Deploy SeldonDeployment
        command: |
          VERSION="$(echo $CIRCLE_SHA1 | cut -c -7)" && sed -ibak 's/VERSION/'"$VERSION"'/g' seldon/cartpole_seldon.json
          kubectl apply -f seldon/cartpole_seldon.json -n seldon

workflows:
  version: 2
  build:
    jobs:
    - "3.5"
    - "3.6"
        requires:
        - "3.5"
    - gce:
        requires:
        - "3.6"
        filters:
          branches:
            only: master